name: demo
channels:
- conda-forge
- openeye
- nodefaults
dependencies:
- openeye-toolkits  # optional! just to get faster AM1-BCC
- ruff *
- openff-toolkit-examples ==0.16.9
- openfe ==1.4.0
- konnektor
- python 3.11.*
- nglview *
- pymol-open-source
- jupyterlab *
- intake
- zarr >=3.0.0
- molfeat
- datamol
- mordredcommunity
- lightgbm
- seaborn
- splito
- umap-learn
- modal
- chemprop >= 2.1.1
- pytorch # <2.4.0
- pytorch-lightning
- wandb
- statsmodels
- mdanalysis
- pytorch_geometric
- pytorch_cluster
- pytorch_scatter
- pytorch_sparse
- h5py
- e3nn
- ase
- loguru
- seaborn
- pip:
  - openadmet-toolkit @ git+https://github.com/OpenADMET/openadmet-toolkit.git
  - openadmet-models @ git+https://github.com/OpenADMET/openadmet-models.git
  - phx-class-registry
  - email-validator
  - git+https://github.com/OpenADMET/mtenn.git@remove_dgl
  - openff-pablo @ git+https://github.com/openforcefield/openff-pablo.git@v0.0.1a1
  - pyxdg
